/*
Jenkins job does reproducible build compare.
*/
import groovy.json.JsonOutput

env.NODE_LABEL = 'dockerBuild&&linux&&x64'
pipeline {
    agent { label NODE_LABEL }
     parameters {
        string(name: 'COMPARED_JOB_NAME', defaultValue: '', description: 'Compared nightly build job name')
    }

    stages {
        stage('Prepare') { //Copy artifacts, reset parameters,trigger build and copyArtifacts
            steps {
                cleanWs()
                checkout scm
                copyArtifacts excludes: '**/OpenJDK*-sbom*metadata.json,**/OpenJDK*-jdk-sources*.tar.gz', 
                                filter: '**/OpenJDK*-jdk*.tar.gz,**/OpenJDK*-jdk*.zip,**/OpenJDK*-sbom*.json',
                                fingerprintArtifacts: true, 
                                flatten: true, 
                                projectName: "${params.COMPARED_JOB_NAME}",
                                target: 'original/',
                                selector: specific("256")
                script {
                    timeout(time: 2, unit: 'HOURS') {
                                copyArtifacts(
                                    projectName: "${params.COMPARED_JOB_NAME}",
                                    selector:specific("257"),
                                    excludes: '**/OpenJDK*-jdk-sources*.tar.gz',
                                    filter: '**/OpenJDK*-jdk*.tar.gz,**/OpenJDK*-jdk*.zip',
                                    target: 'reproduced/',
                                    fingerprintArtifacts: true,
                                    flatten: true
                                )
                            }
                    if (!COMPARED_JOB_NAME.contains('linux')) {
                        NODE_LABEL="win2012&&vs2019&&build&&windows&&x64"
                    }
                    archiveArtifacts artifacts: '**/OpenJDK*-jdk*.tar.gz,**/OpenJDK*-jdk*.zip', fingerprint: true
                }
            }
        }
        stage('Compare') {
            agent { label NODE_LABEL }
            steps {
                copyArtifacts filter: '**/OpenJDK*-jdk*.tar.gz,**/OpenJDK*-jdk*.zip',
                    fingerprintArtifacts: true, 
                    projectName: env.JOB_NAME,
                    selector: specific("${env.BUILD_NUMBER}")
                checkout([$class: 'GitSCM', branches: [[name: 'cygwin']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "temurin-build"]], submoduleCfg: [], userRemoteConfigs: [[url: "https://github.com/sophia-guo/openjdk-build.git"]]])
            
                script {
                    if (COMPARED_JOB_NAME.contains('windows')) {
                        def originalJDKFile = findFiles(glob: "original/*.zip")
                        def reproducedJDKFile = findFiles(glob: "reproduced/*.zip")
                        def untarOriginalJDK = sh returnStatus: true, script: "cd original && temp=`mktemp -d` && unzip -d ${temp} ${originalJDKFile[0].name} && mv ${temp}/*/* ./ && rmdir ${temp}/* ${temp}"
                        if (untarOriginalJDK != 0 ) {
                            currentBuild.result = 'UNSTABLE'
                            error " Unzip ${originalJDKFile[0].path} failed"
                            return
                        }
                        def untarReproducedJDK = sh returnStatus: true, script: "cd reproduced && temp=`mktemp -d` && unzip -d ${temp} ${reproducedJDKFile[0].name} && mv ${temp}/*/* ./ && rmdir ${temp}/* ${temp}"
                        if (untarReproducedJDK != 0 ) {
                            currentBuild.result = 'UNSTABLE'
                            error " Unzip ${originalJDKFile[0].name} failed"
                            return
                        }
                        sh "find . -type f -name 'OpenJDK*-jdk*.zip' -delete"
                    } else {
                        def originalJDKFile = findFiles(glob: "original/*.tar.gz")
                        def reproducedJDKFile = findFiles(glob: "reproduced/*.tar.gz")
                        def untarOriginalJDK = sh returnStatus: true, script: "tar xzf ${originalJDKFile[0].path} --strip-components=1 -C original"
                        if (untarOriginalJDK != 0 ) {
                            currentBuild.result = 'UNSTABLE'
                            error " Untar ${originalJDKFile[0].name} failed"
                            return
                        }
                        def untarReproducedJDK = sh returnStatus: true, script: "tar xzf ${reproducedJDKFile[0].path} --strip-components=1 -C reproduced"
                        if (untarReproducedJDK != 0 ) {
                            currentBuild.result = 'UNSTABLE'
                            error " Untar ${reproducedJDKFile[0].name} failed"
                            return
                        }
                        sh "find . -type f -name 'OpenJDK*-jdk*.tar.gz' -delete"
                    }
                    try {
                        dir('temurin-build/tooling') {
                            def rc = 0
                            if (COMPARED_JOB_NAME.contains('linux')) {
                                rc = sh returnStatus: true, script: "./repro_compare.sh temurin ${WORKSPACE}/original temurin ${WORKSPACE}/reproduced Linux"
                            } else if (COMPARED_JOB_NAME.contains('mac')) {
                                // mac
                                //rc = sh returnStatus: true, script: "./repro_compare.sh temurin ${WORKSPACE}/original temurin ${WORKSPACE}/reproduced Darwin"
                                echo 'todo mac build comparison'
                            } else if (COMPARED_JOB_NAME.contains('windows')) {
                                //windows
                                echo 'todo windows build comparison'
                                rc = sh returnStatus: true, script: "./repro_compare.sh temurin `pwd`/../../original temurin `pwd`/../../reproduced CYGWIN"
                            }
                            if (rc != 0) {
                                currentBuild.result = 'FAILURE'
                                echo 'Failed: two builds are not the same! Please see the archived repro_diff.out.'
                            } else {
                                echo 'Success: two builds are the same!'
                            }
                            archiveArtifacts artifacts: "**/repro_diff.out"
                        }
                    } catch (Exception err) {
                        echo err.getMessage()
                        currentBuild.result = 'FAILURE'
                    } finally {
                        cleanWs()
                    }
                }
            }
        }
    }
}